OFFICIAL_7_INCH_PI_SCREEN = 1
MY_MONITOR = 2

SCREEN_TYPE = OFFICIAL_7_INCH_PI_SCREEN
#SCREEN_TYPE = MY_MONITOR

if SCREEN_TYPE == OFFICIAL_7_INCH_PI_SCREEN:
    WIN_WIDTH = 800
    WIN_HEIGHT = 480
    LABEL_FONT_SIZE=33
    LABLE_FONT_SIZE_SML = 20
    LABEL_SPACER_HORIZONTAL = 4
    LABEL_SPACER_VERTICAL_TOP = WIN_HEIGHT * 0.02
    LABEL_SPACER_VERTICAL_MIDDLE = WIN_HEIGHT * 0.15
    LABEL_SPACER_VERTICAL_BOTTOM = WIN_HEIGHT * 0.92
    LABEL_ORIGIN_X_TOP = WIN_WIDTH * 0.008
    LABEL_ORIGIN_X_MIDDLE = WIN_WIDTH * 0.42
    LABEL_ORIGIN_X_BOTTOM = WIN_WIDTH * 0.43

    #VIEWABLE_HEIGHT_R must always be less than WIN_HEIGHT
    VIEWABLE_HEIGHT_R = 120 #for overhead        
    VIEWABLE_WIDTH_R = 400 #for side view
    STOPWATCH_ORIGIN_X = (WIN_WIDTH * 0.01) + LABEL_SPACER_HORIZONTAL
    STOPWATCH_FONT_SIZE = 35

    SYSTEM_TIME_FONT_SIZE = 15
    SCREEN_MSG_FONT_SIZE = 25
    BUTTON_MSG_FONT_SIZE = 35
    OFFSCREEN_MARKER_FONT_SIZE = 20
    CHECKPOINT_INTERVAL = 200
    CHECKPOINT_MARKER_FONT_SIZE = 15
    SIDE_VIEW_CHECKPOINT_MARKER_FONT_SIZE = 15
    HELP_FONT_SIZE = 20
    BUFFER = 40
    BUOY_SIZE = 4
else:
    WIN_WIDTH = 1600
    WIN_HEIGHT = 960
    #VIEWABLE_HEIGHT_R must always be less than WIN_HEIGHT
    VIEWABLE_HEIGHT_R = 75
    LABEL_FONT_SIZE=21
    LABEL_SPACER_VERTICAL = WIN_HEIGHT * 0.09
    LABEL_SPACER_HORIZONTAL = 5
    LABEL_ORIGIN_X = (WIN_WIDTH * 0.75) + LABEL_SPACER_HORIZONTAL
    SYSTEM_TIME_FONT_SIZE = 30
    STOPWATCH_FONT_SIZE = 60
    SCREEN_MSG_FONT_SIZE = 30
    BUTTON_MSG_FONT_SIZE = 45
    OFFSCREEN_MARKER_FONT_SIZE = 25
    CHECKPOINT_INTERVAL = 200
    CHECKPOINT_MARKER_FONT_SIZE = 15
    SIDE_VIEW_CHECKPOINT_MARKER_FONT_SIZE = 25
    HELP_FONT_SIZE = 20
    BUFFER = 50
    BUOY_SIZE = 5

TEST = 1
REAL = 2
#SETUP_TYPE = TEST
SETUP_TYPE = REAL
if SETUP_TYPE == TEST:
    NUM_SECONDS_TIMEOUT = 30000
    NUM_SECONDS_BEFORE_TIMEOUT_WARNING = 15
    NUM_SECONDS_BEFORE_TIMEOUT_CRITICAL_WARNING = 10
    NUM_SECONDS_BEFORE_END_SESSION_WARNING = 9
    #don't change this
    NUM_SECONDS_INACTIVITY_PERIOD = 3
else:
    NUM_SECONDS_TIMEOUT = 30
    NUM_SECONDS_BEFORE_TIMEOUT_WARNING = 15
    NUM_SECONDS_BEFORE_TIMEOUT_CRITICAL_WARNING = 10
    NUM_SECONDS_BEFORE_END_SESSION_WARNING = 9
    NUM_SECONDS_INACTIVITY_PERIOD = 6

PRE_BATCH = 1
ON_THE_FLY_BATCH = 2

LEFT = 1
MID = 2

BUOY_COLOUR = (249,248,67)
HALF_WIDTH = int(WIN_WIDTH / 2)
HALF_HEIGHT = int(WIN_HEIGHT / 2)
DISPLAY = (WIN_WIDTH, WIN_HEIGHT)
BUOY_AREA_MIN_X = BUFFER
BUOY_AREA_MAX_X = WIN_WIDTH - BUFFER
BUOY_AREA_WIDTH = BUOY_AREA_MAX_X - BUOY_AREA_MIN_X

PLAYER_START_R = 0
GHOST_START_R = 0

DEPTH = 32

#values used by the event (GUI) q
BUTTON_MSG = -6
SYSTEM_DATE = -4
MULTILINE_MSG = -3
SCREEN_MSG = -2
STOPWATCH_UPT = -1
PLAYER_UPT = 0
STROKE_UPT = 1
GHOST_UPT = 2
FISH_UPT = 3
PLAYER_BOATWASH = 4
PLAYER_SPEED = 5
PLAYER_DISTANCE = 6
RESET = 101
EXIT = -99
SHUTDOWN = -98

#values used by the data q
MAX_PLAYERS = 86
TRIAL_TIME = 87
FISH = 88
RESET_SESSION = -1
STOP_SESSION = -2
REFRESH_RATE = -3
SESSION_COMPLETED = -4

#fish swimming directions
LEFT_TO_RIGHT = 1
RIGHT_TO_LEFT = 2

WHITE = (255,255,255)
RED = (255,0,0)
GREEN = (85,255,0)
BLACK = (0,0,0)
YELLOW = (248,248,0)
GREY = (214,211,222)
BLUE = (16,75,243)
PURPLE = (194,74,223)
PURPLE2 = (165,23,199)
PALE_RED = (244,23,0)
REDDISH = (244,2,100)
ORANGE = (247,143,23)
WASH_COLOUR = WHITE
STOPWATCH_COLOUR = WHITE

FANWHEEL_CHANNEL = 15
IR_ONE = 1
IR_ONE_CHANNEL = 16
IR_ONE_LED_CHANNEL = 38
IR_TWO = 2
IR_TWO_CHANNEL = 12
IR_TWO_LED_CHANNEL = 36
IR_THREE = 3
IR_THREE_CHANNEL = 18
IR_THREE_LED_CHANNEL = 40

#FANWHEEL_CHANNEL = 15
#IR_ONE = 1
#IR_ONE_CHANNEL = 16
#IR_ONE_LED_CHANNEL = 38
#IR_TWO = 2
#IR_TWO_CHANNEL = 12
#IR_TWO_LED_CHANNEL = 36
#IR_THREE = 3
#IR_THREE_CHANNEL = 18
#IR_THREE_LED_CHANNEL = 40

MATRIX = [['1','2','3','A'],
          ['4','5','6','B'],
          ['7','8','9','C'],
          ['*','0','#','D']]

ROW = [37,35,33,31]
COL = [29,23,21,19]

NUM_ROWS = 6

OVERHEAD = 1
SIDE = 2
GAME_VIEW = 129

OVERHEAD_PLAYER_IMAGE_PATH = "./resources/player_large"
OVERHEAD_GHOST_IMAGE_PATH = "./resources/ghost_large"
SIDE_PLAYER_IMAGE_PATH = "./resources/side_view_boats/350"
SIDE_GHOST_IMAGE_PATH = "./resources/side_view_boats"
        		
GHOST_JSON_PATH = "./JSON_sessions"
FISH_IMAGE_PATH = "./resources/fish"
SETTINGS_JSON_FILE = "./settings.json"

DRIVE_STROKE = 1
RECOVERY_STROKE = 2

POINT_UP = 1
POINT_DOWN = 2
POINT_LEFT = 3
POINT_RIGHT = 4
POINT_AHEAD = 5
POINT_BACK = 6

SELECTOR = 800
PERSONAL_BESTS = 801
PERSONAL_AVERAGES = 802
PERSONAL_WORSTS = 803

NO_GHOST_FILES_PRESENT = -1

MAX_FORWARD_RANGE = 40
MAX_BACKWARD_RANGE = -40


